language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.5.1
  - DJANGO_VERSION=1.6.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - python setup.py -q install
script: cd example && python manage.py test text_admin
